### ISSUE TITLE
Types of materials should be created so that the association can exist

### ISSUE THREAD

**Issue by cchable** [InfotelGLPI/positions#11]
I can't use setup/Association : picture / types of equipment
![snip_20151214120711](https://cloud.githubusercontent.com/assets/5113318/11779434/5d9e8a62-a25b-11e5-9348-1c0211a329b1.png)

**Comment by tsmr** [comment]
Can you try with last master ?

**Comment by cchable** [comment]
Yes.
With GLPI 0.90, it does not work.
With GLPI 0.85, it's work.

**Comment by tsmr** [comment]
with https://github.com/InfotelGLPI/positions/archive/master.zip ?

**Comment by cchable** [comment]
Yes, version of file : 11/12/2015

**Comment by tsmr** [comment]
Can you try to revert this update ?
https://github.com/InfotelGLPI/positions/commit/f722c2147ad495514e86059c3b28ad2f62992630#diff-8020659f4b905c3140943fb617cb1650

front/upload.php ?

**Comment by cchable** [comment]
I try it, but the same
The directory "files\_plugins\positions\pics" is empty in my 0.90, not in my 0.85...
If I put the image file in this directory, it's good, but the "i" is still there.
![snip_20151214162835](https://cloud.githubusercontent.com/assets/5113318/11785043/f17a4b62-a27f-11e5-8671-9fa0d9dbbadf.png)

**Comment by cchable** [comment]
Nobody here...?
Plus personne... ?

**Comment by tsmr** [comment]
Have you errors in apache or glpi logs ?

**Comment by cchable** [comment]
Hello TSMR,

I take two weeks of vacation.
Resumption January 4.

Happy New Year

**Comment by cchable** [comment]
Hello TSMR,

I'll be always back ;-)

So I checked the logs, without errors...

Also, when I want to place an item on the map, it does not find when I'm making images / Computer Associations
![snip_20160104151757](https://cloud.githubusercontent.com/assets/5113318/12091323/80ba33b0-b2f6-11e5-9637-e729a9a69420.png)
![snip_20160104151627](https://cloud.githubusercontent.com/assets/5113318/12091367/e3f14568-b2f6-11e5-995e-5aa97f48014c.png)

**Comment by tsmr** [comment]
The computer have the same location as the map ?

**Comment by cchable** [comment]
I found : the x and y coordinates of computer were -1000 and -225...

The loading of the picture is still not functionally

**Comment by amma35** [comment]
Can you test with this release https://github.com/InfotelGLPI/positions/releases/tag/4.3.1 ?

**Comment by cchable** [comment]
Hello Amma,

The loading of the picture is ok now.

Another problem :
The new field locations_id in table glpi_plugin_positions_positions stay always at 0. So, I can't place an objet on the map.

**Comment by amma35** [comment]
Have you errors in apache or glpi logs ?

**Comment by TitanLV** [comment]
Greetings. I got same problem as cchable - cant add items - no maches found

and I am noob in GLPI/Linux. Just started to set up this tool recently.

GLPI 9.1.2
Cartography 4.3.1
![image](https://cloud.githubusercontent.com/assets/26477888/25017092/2500fcb2-208b-11e7-8e24-af450a0a5edc.png)

**Comment by TitanLV** [comment]
Just noticed: 
I created new test PC entry in GLPI and it was shown in Create coordinates/Computer.
Than I deleted few Computers from GLPI  and re imported them from OCSNGInventory.
New PC now could be added to map with success.
Any tips how to fix it on old computer items in GLPI?

**Comment by amma35** [comment]
Please open a new issue for your problem that does not concern the main issue of the topic to get an answer.
