### ISSUE TITLE
I cant setup positions

### ISSUE THREAD

**Issue by pwnz22** [InfotelGLPI/positions#12]
I cant understand how to add a map and then objects in it. Can someone give a tutorial for this. Im adding objects to positions and always see message "No location has a configured map".

![Main window](https://i.gyazo.com/8f270d1c0d6ce760d8fd2adb4062d585.png)

**Comment by pwnz22** [comment]
Need to add map in document

**Comment by tsmr** [comment]
Open Setup > Dropdowns > Location - Tab Documents
