### ISSUE TITLE
 Fix display dropdown

### ISSUE THREAD

**Issue by amma35** [InfotelGLPI/positions#14]
Fix display dropdown

![dropdown](https://cloud.githubusercontent.com/assets/15138371/19211813/e07fb5e8-8d45-11e6-9f85-d2bbe417d7dd.PNG)

**Comment by jrmorera** [comment]
![associate images](https://cloud.githubusercontent.com/assets/22928019/19506170/65b10242-9586-11e6-8ccd-38486bb7f7f7.JPG)
Still experiencing issues while trying to associate images to types. I have uploaded the latest master Oct 18, 2016.

**Comment by jrmorera** [comment]
Yey, thanks amma35, you rock!!!
It works perfectly now.
