### ISSUE TITLE
Icons shifting on map when loaded

### ISSUE THREAD

**Issue by plight** [InfotelGLPI/positions#15]
When we place racks on the map, if the map is reloaded, sometimes the objects shift slightly.  This causes issues with readability with the rack names.

Version 4.2.1

**Comment by amma35** [comment]
see #20 
Can you test with this fix: : https://github.com/InfotelGLPI/positions/commit/75e9073149ffae62683a2dc0dfd62e0f1bb43ba4

**Comment by jpnr79** [comment]
change the code :
1273 - 1274 du fichier position.class.php
1273 $node['x'] = $node['x_coordinates'] ; //suppression du+1; "" to +0
1274 $node['y'] = $node['y_coordinates'] ; //suppression du+1; "" to +0

**Comment by amma35** [comment]
corrected see https://github.com/InfotelGLPI/positions/commit/75e9073149ffae62683a2dc0dfd62e0f1bb43ba4
