### ISSUE TITLE
Exactly the same occurs with me

### ISSUE THREAD

**Issue by maramaca** [InfotelGLPI/positions#16]
Works on 0.8x, nothing in 9.1

"Failed to load" when selecting computer for adding to map.

Any idea?

**Comment by tsmr** [comment]
Modify file like this :  
https://github.com/InfotelGLPI/positions/commit/3fff62f20b36267aa299c0cba94fb7e2943644a0

**Comment by amma35** [comment]
Can you test with this release [https://github.com/InfotelGLPI/positions/releases/tag/4.3.1](url)  ?

**Comment by maramaca** [comment]
Works perfect! Many thanks and nice job.
