### ISSUE TITLE
loading failed

### ISSUE THREAD

**Issue by satyan01** [InfotelGLPI/positions#17]
hello when i want to associate a computer or printer or others I have nothing in dropdown list

![image](https://cloud.githubusercontent.com/assets/15144026/21014501/9be65c90-bd5e-11e6-9abd-adda4e22dc0c.png)

**Comment by tsmr** [comment]
Which version of plugin please ?

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/21014723/6695e60e-bd5f-11e6-8ddf-b7c651c1d4b2.png)

**Comment by satyan01** [comment]
glpi 9.1

**Comment by tsmr** [comment]
Have you errors in logs ? glpi & web server ?

**Comment by satyan01** [comment]
2016-12-08 16:13:47 [854@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: use_view_all_object
  Backtrace :
  plugins\positions\inc\config.class.php:58          
  plugins\positions\front\config.form.php:43         PluginPositionsConfig::showForm()

2016-12-08 16:16:51 [854@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: table
  Backtrace :
  plugins\positions\ajax\dropdownValue.php:40

**Comment by tsmr** [comment]
Hum.. your first erro sound like a problem on plugin install

can you launch these : 

```
CREATE TABLE `glpi_plugin_positions_configs` (
               `id` int(11) NOT NULL auto_increment,
               `use_view_all_object` tinyint(1) NOT NULL default '0',
               PRIMARY KEY  (`id`)
            )ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `glpi_plugin_positions_configs` (`id`,`use_view_all_object`) VALUES ('1', '0');
```

**Comment by satyan01** [comment]
already exist 

![image](https://cloud.githubusercontent.com/assets/15144026/21018829/aec3da1c-bd6e-11e6-93a7-23b08a417f79.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/21018961/362ce3d6-bd6f-11e6-929c-fe45116bd6f9.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/21019184/db617506-bd6f-11e6-9fcf-e501be1a2b39.png)

**Comment by tsmr** [comment]
do INSERT so

Can you try this too ?

https://github.com/InfotelGLPI/positions/issues/14

**Comment by satyan01** [comment]
sorry i  don't understand what I have to do

**Comment by tsmr** [comment]
Do INSERT
```
INSERT INTO `glpi_plugin_positions_configs` (`id`,`use_view_all_object`) VALUES ('1', '0');
```

And modify file like this :  
https://github.com/InfotelGLPI/positions/commit/3fff62f20b36267aa299c0cba94fb7e2943644a0

**Comment by satyan01** [comment]
fixed. Great Thanks
