### ISSUE TITLE
error no map

### ISSUE THREAD

**Issue by satyan01** [InfotelGLPI/positions#19]
2016-12-13 11:51:46 [@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: glpiactiveprofile
  Backtrace :
  plugins\positions\front\map.php:40

**Comment by amma35** [comment]
What version of the plugin and GLPI?

**Comment by satyan01** [comment]
when I add a computer on a map the map disappear, I have to click again on see map

**Comment by satyan01** [comment]
and often the message "The action you have requested is not allowed." after a location selected to see the map

**Comment by satyan01** [comment]
2016-12-13 11:51:44 [@UNGSRVGVA118]
  *** MySQL query error:
  SQL: SELECT *
             FROM `glpi_plugin_positions_positions`  WHERE   ( `glpi_plugin_positions_positions`.`entities_id` IN ()  )  
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')  )' at line 2
  Backtrace :
  inc\db.function.php:430                            
  plugins\positions\inc\position.class.php:840       getAllDatasFromTable()
  plugins\positions\inc\position.class.php:893       PluginPositionsPosition::getMapItems()
  plugins\positions\front\coordinates.form.php:44    PluginPositionsPosition::showMap()
2016-12-13 12:01:01 [854@UNGSRVGVA118]
  *** MySQL query error:
  SQL: DELETE FROM `glpi_tickets` WHERE `itemtype` = \'PluginPositionsPosition\' ;
  Error: Unknown column 'itemtype' in 'where clause'
  Backtrace :
  plugins\positions\hook.php:186                     
  inc\plugin.class.php:639                           plugin_positions_uninstall()
  front\plugin.form.php:49                           Plugin->uninstall()

**Comment by satyan01** [comment]
I have place all my computers, when I come back all my work has disappear.

**Comment by amma35** [comment]
I replicate the bug when adding an object and the map disappears.

After adding objects to the map, did you click the "Change the coordinates" button?

**Comment by satyan01** [comment]
yes

**Comment by satyan01** [comment]
effectively when i click on change the coordinates it keep changes. thx
