### ISSUE TITLE
Les coordonnées X et Y des objets dans la map sont incrémentés de 1 à chaque validation

### ISSUE THREAD

**Issue by lolosoftware** [InfotelGLPI/positions#20]
- version of the plugin  4.3.1
- version of your GLPI 9.1
- Valider les coordonnées sur la carte et observer les coordonnées d'un objet dans sa fiche pour observer qu'ils ont été incrémenté de 1 en X et Y pour reproduire le problème.

J'ai observé qu'à chaque fois que je rajoutais un objet sur la carte et que je validais les coordonnées l'ensemble des objets se retrouvent décalés un peu plus bas en bas à droite de la position précédente. Après observation les coordonnées des fiches se retrouvent incrémentés de 1 à chaque validation.

J'ai réussi à contourner le problème en modifiant les lignes 1273 - 1274 du fichier position.class.php
 1273           $node['x']         = $node['x_coordinates'] ; //suppression du+1;
 1274          $node['y']         = $node['y_coordinates'] ; //suppression du+1;

**Comment by jpnr79** [comment]
If I supress the +1, if got errors on the display item without no name or description, so i put in my +0

**Comment by jpnr79** [comment]
change the code : 
1273 - 1274 du fichier position.class.php
1273 $node['x'] = $node['x_coordinates'] ; //suppression du+1; "" to +0
1274 $node['y'] = $node['y_coordinates'] ; //suppression du+1; "" to +0
