### ISSUE TITLE
Put field "Comments" in Configuring the display materials

### ISSUE THREAD

**Issue by magaiverpr** [InfotelGLPI/positions#24]
I have informations in field "comments" in the assets and Network outlets that will be great to show in the informations, configured in that field.

**Comment by magaiverpr** [comment]
Tested here, but netpoints still don't show comments in the Information tab.

**Comment by amma35** [comment]
Do you have any examples? 
The comments field has been added for the objects Computer, Printer, NetworkEquipment, Monitor, Peripheral and Phone.

**Comment by magaiverpr** [comment]
![glpi - cartografia - 1 - mozilla firefox](https://user-images.githubusercontent.com/10533823/35868051-9a862078-0b42-11e8-99a6-b03385e415fa.jpg)
![glpi - cartografia - mozilla firefox](https://user-images.githubusercontent.com/10533823/35868059-a116e58a-0b42-11e8-8102-8babafe33a06.jpg)

**Comment by amma35** [comment]
This is normal as specified in my previous post, I didn't add all the objects: 

> The comments field has been added for the objects Computer, Printer, NetworkEquipment, Monitor, Peripheral and Phone.

I can add for all objects but not all objects have the comment field.

**Comment by magaiverpr** [comment]
Worked, thanks!
