### ISSUE TITLE
GLPI 9.2 compliance

### ISSUE THREAD

**Issue by actikool** [InfotelGLPI/positions#26]
hello, do you know if this pluggin is glpi 9.2 compliant ?

**Comment by amma35** [comment]
No, this version is under development.

**Comment by eduardospinola** [comment]
When will the launch be?

**Comment by amma35** [comment]
We are in the testing period on the master branch.
You can test this version but it is not the final version.

**Comment by amma35** [comment]
see https://github.com/InfotelGLPI/positions/releases/tag/4.4.0
