### ISSUE TITLE
Adding more than 100 items to a map (dropdown search/fill bug).

### ISSUE THREAD

**Issue by smithj4** [InfotelGLPI/positions#27]
GLPI version 9.2.2 with positions plugin version 4.4.0.

When going to the plugin setup and when trying to add new items to a map, first select the item type, like rack enclosure, then another dropdown appears with all items of that type. The dropdown only displays the first 100 matching items, and when scrolling to the last item, it searches again to add more to the dropdown, but the new items do not continue where it last stopped, it appears to just repeat the same search and add a duplicate list of the first 100 items. So it appears you cannot add more than 100 items to a map.

**Comment by amma35** [comment]
Hi,

The bug is a GLPI bug, see https://github.com/glpi-project/glpi/issues/2222
