### ISSUE TITLE
Picture not shown except when creating a sub-item

### ISSUE THREAD

**Issue by Megachip** [InfotelGLPI/positions#28]
- plugin: 4.4.0
- GLPI: 9.2.1

1. uploaded a png document to the location. (same on jpeg)
1. going to tools -> catrographie
1. select the location and put on see the map

only see the question mark:
<img width="1347" alt="bug" src="https://user-images.githubusercontent.com/487352/38366749-13622f52-38e1-11e8-941f-58c2c828ba1e.png">

When creating a sub entry, it shown the image, but failed on creating the temp image for the subentry.

**Comment by amma35** [comment]
Hi,

Have you errors in logs ? glpi & web server ?

**Comment by Megachip** [comment]
@amma35 nothing. Neither in SQL nor in Error (Apache) or in php.

**Comment by lolosoftware** [comment]
HI,
I advice you tu look at the web address application in the top of the general configuration. I have the problem if is not exactly the same path you are using (ex : if i use ip in order to dns => not look image)

**Comment by Megachip** [comment]
@lolosoftware that it.

@amma35 could that be fixed? It should work with every url.

**Comment by amma35** [comment]
Do you have an error in the browser console when you start viewing the map?

**Comment by Megachip** [comment]
> Do you have an error in the browser console when you start viewing the map?
AFAIR no error in logs or in browser. But will recheck. @lolosoftware do you remember any errors?

**Comment by aze789** [comment]
Did you fix the problem ??

**Comment by Eon9D** [comment]
Solution from "lolosoftware"
> I advice you tu look at the **web address application in the top of the general configuration**. I have the problem if is not exactly the same path you are using (ex : if i use ip in order to dns => not look image)

**Comment by aze789** [comment]
another solution ??

**Comment by amma35** [comment]
No, there is no other solution, this is a prerequisite for good work: https://github.com/InfotelGLPI/positions/wiki/FR---01-Configuration-du-plugin
