### ISSUE TITLE
Resize image or objects

### ISSUE THREAD

**Issue by Megachip** [InfotelGLPI/positions#30]
Dear positions team,

is it possible to resize the floor plans or the size of the objects?

**Comment by amma35** [comment]
No the size of the images are fixed. 
The size of the plans is displayed according to the elements that compose it

**Comment by Megachip** [comment]
Thats bad. ATM sometimes a network outlet is bigger than my whole room. 

Is there any best way/usecase how to choose the ideal filesize and how to set coordinates? 

Why huge floorpans are centered as small objects in the middle?

**Comment by amma35** [comment]
I misspoke the size of the image is fixed to the addition but then you can change it. 

![position](https://user-images.githubusercontent.com/15138371/42620874-86f9288a-85bc-11e8-88d5-8d7e254bc184.png)
![position1](https://user-images.githubusercontent.com/15138371/42620876-88ee41fc-85bc-11e8-91ca-6edaa5c02b62.png)

**Comment by Megachip** [comment]
Tried this. But Font size stays the same. 
Seems better to change the size of the background (e.g. the cutted out image). (or save an zoom/scale level)
