### ISSUE TITLE
Possibility to change the labelsize field to decimals

### ISSUE THREAD

**Issue by satelsa** [InfotelGLPI/positions#31]
* Version of the plugin :  4.4.0
* Version of your GLPI :  9.2.2

I have changed the labelSize field of the table glpi_plugin_positions_positions to be able to use decimals in the texts of the objects, it works correctly in those I have tried.
Is it possible to add this improvement to the add-on?.
Thank you

**Comment by amma35** [comment]
The LabelSize field is used to define the text size.
What value did you define?

**Comment by satelsa** [comment]
Table 'glpi_plugin_positions_positions'    field 'labelSize'  it is currently  Integer.
If it could be definitively put as 'decimal' it would allow the size of the texts to be adjusted a bit more.
The tests I've done have worked well and so the text can be adjusted a bit more according to the image size
