### ISSUE TITLE
No location has a configured map/No location selected

### ISSUE THREAD

**Issue by fattuen** [InfotelGLPI/positions#34]
HI Plugin team 

I found an issue when first use this plugin, would you mind to help me to solve it?

------------
* Version of the plugin : 4.4.0
* Version of your GLPI : 9.2.3

* Steps to reproduce (which actions have you made) :

when click cartographies, it show "No location has a configured map" 
then add new Cartography
click "+" next to tab "Cartographies"
Enter below information s
Name:"test"
Associated Element: Location --> M5 building
Then 
Error "No location selected"

* Expected result :

new  cartography created 

* Actual result :

Error "No location selected"

* Screenshot of the problem (if pertinent) :

![sample 1](https://user-images.githubusercontent.com/1551380/40105643-28049da4-5926-11e8-9e42-0ad4641d6fc2.png)
![sample 2](https://user-images.githubusercontent.com/1551380/40105649-2cd4820e-5926-11e8-8026-5d65377f2bd8.png)

Patrick

**Comment by Eon9D** [comment]
No location has a configured map
Did you uploaded a map ?
.../front/location.php -> select location -> open documents tab -> upload map there

**Comment by fattuen** [comment]
Thanks  solved:)

**Comment by Eon9D** [comment]
@fattuen Please close the issue then. Thanks
