### ISSUE TITLE
Which filetypes are supported for ground floors?

### ISSUE THREAD

**Issue by Megachip** [InfotelGLPI/positions#35]
Is it anywhere documented?

**Comment by aze789** [comment]
You can use JPG / JPEG / GIF / PJPEG and PNG

**Comment by aze789** [comment]
I don't think you can do it with a PDF

**Comment by amma35** [comment]
For the moment, this is not possible with a PDF only with images.

**Comment by Megachip** [comment]
Seems PDFs works fine. Sadly, cause it ignores my image file which is assigned to the location and choose the pdf (table) as ground plan.
