### ISSUE TITLE
Unable to add a document on a place

### ISSUE THREAD

**Issue by eddogniemad** [InfotelGLPI/positions#38]
* Version of the plugin : 4.4.0
* Version of your GLPI : 9.2.2

Dear, 
After the plugin is installed, I'm unable to add a document when creating or modifying a place.
There isn't any field to add a document
![2018-07-17 17_46_44-glpi - lieux - -1](https://user-images.githubusercontent.com/40659088/42829003-75b514d6-89e9-11e8-8e4d-332e9db6ff93.png)

I check in preferences but I didn't see anything with this. is there something I missed ?

Thanks for your help

**Comment by amma35** [comment]
Hi,

There is a "Document" tab which is not the plugin tab, so you need the rights on the documents.

**Comment by eddogniemad** [comment]
I made the test with a super-admin account which have rights on documents

**Comment by eddogniemad** [comment]
![2018-07-17 17_46_44-glpi - lieux - -1](https://user-images.githubusercontent.com/40659088/42940874-338675b4-8b5b-11e8-8aec-80673ceee802.png)
As you can see, all is ok on the documents rights and anyway, nothing appear on the plugin tab.
Is there something that I missed ?
Thanks a lot by advance

**Comment by amma35** [comment]
You must first create the location to have the tabs

**Comment by amma35** [comment]
I'm closing for now without answer, feel free to reopen if issue persists.
