### ISSUE TITLE
'Cartography - name' in objet view doesn't work properly

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/positions#4]
Version 4.0.0 (0.84)

Go to an object type managed by the plugin, let's say : Networks
Add to the view of Networks : Cartography-Name
In some cases, the column 'Cartography-Name' remains empty, or points towards a position which is not the correct one !

When the position name (by default equal to the object name) contains one or more digits (or a -, and maybe other special character), it adds these digits to the position ID, and thus doesn't find it, or find another position.
Ex : position name = 'network 1', ID 6
it looks for position 16.

Version 4.1.0 (0.85)

add 'Cartography-Name' to the view generate systematic php errors at display of the list of items, whether the object has a position or not.

PHP Notice(8): Undefined index: ITEM_9
Backtrace :
plugins/positions/hook.php:300 
inc/search.class.php:4360 plugin_positions_giveItem()
inc/search.class.php:1068 Search::giveItem()
inc/search.class.php:93 Search::constructDatas()
inc/search.class.php:77 Search::showList()
front/phone.php:40 Search::show()

**Comment by amma35** [comment]
Fixed in the latest version
