### ISSUE TITLE
GLPI 9.5

### ISSUE THREAD

**Issue by Alwaysin** [InfotelGLPI/positions#51]
Kindly asking for a release for 9.5 :)

* Version of the plugin : 4.6

* Version of your GLPI : 9.5

* Steps to reproduce (which actions have you made) : nothing, kept the plugin as I had it

* Expected result : plugin working

* Actual result : Ce plugin requiert GLPI >= 9.4.

**Comment by KongNan** [comment]
Positions is good! GLPI 9.5 is good! 
Positions + GLPI 9.5 is Great!

**Comment by keha35** [comment]
Thanks for the reply.
Then i'm closing the issue.

**Comment by Alwaysin** [comment]
On my GLPI installation on the module page I have:

Ce plugin requiert GLPI >= 9.4.

Which means "this plugin requires GLPI >= 9.4".
