### ISSUE TITLE
GLPI 9.5

### ISSUE THREAD

**Issue by Alwaysin** [InfotelGLPI/positions#53]
Follow-up of https://github.com/InfotelGLPI/positions/issues/51

Kindly asking for a release for 9.5 :)

Version of the plugin : 4.6

Version of your GLPI : 9.5

Steps to reproduce (which actions have you made) : nothing, kept the plugin as I had it

Expected result : plugin working

Actual result : Ce plugin requiert GLPI >= 9.4.

**Comment by guinhares** [comment]
do you know when it will be released for version 9.5.1?

**Comment by KongNan** [comment]
or for version 9.5.2?  :D

**Comment by eglyn** [comment]
Same question, is there a chance to have an update to 9.5.2 ?

**Comment by jlmelladovalle** [comment]
It's a shame we cannot use last functionalities with this powerful plugin

**Comment by bacus99** [comment]
Have you tried the latest version?
