### ISSUE TITLE
Canot add computers to the Map

### ISSUE THREAD

**Issue by Opol13** [InfotelGLPI/positions#62]
Hi,

I have problems to add new computers on the Map. When I click on Add in Cartographies section, I have a message : "Aucun lieu sélectionné".
When I go back to Cartography section, UI have default coordinates (-1000,-225) but when I go to Tools/Cartography and that I wand to add this computer to the map, it does not appear in the list !
I am a bit lost as I have old computers appearing but cannot add the new ones.

Version of Glpi : 9.1
Version of Cartography : 4.3.1

**Comment by tsmr** [comment]
Fixed in 6.0.3 version
