### ISSUE TITLE
HTTP ERROR 404 front/netpoint.form.php?id=4

### ISSUE THREAD

**Issue by jcervantes-sipecom** [InfotelGLPI/positions#64]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 
6.0.2

* Version of your GLPI : 
10.0.7

* Steps to reproduce (which actions have you made) :

1. Add a Socket to a map
2. Click or Open the socket recently created.
3. The link is reference to ´/front/netpoint.form.php?id=4´ which is not anymore used in GLPI 10 instead to 9.5

* Expected result :
Open the socket to the correct link reference which is: ´/front/socket.form.php?id=4´

* Actual result :
´HTTP ERROR 404´ because the link reference ´/front/netpoint.form.php´ does not exists anymore.
 

* URL of the page :
/front/netpoint.form.php

* Screenshot of the problem (if pertinent) :

![image](https://user-images.githubusercontent.com/56606032/234398120-5baaecf0-4875-4138-b75f-12564e6827bf.png)

![image](https://user-images.githubusercontent.com/56606032/234398028-1f56f033-8ff1-4e36-8486-24cbb7d43e99.png)

**Comment by tsmr** [comment]
Fixed in 6.0.3 version
