### ISSUE TITLE
Mysql Wrong fileds type

### ISSUE THREAD

**Issue by r0undtrip** [InfotelGLPI/positions#66]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 
6.0.2

* Version of your GLPI : 
10.0.9

* Steps to reproduce (which actions have you made) :
Whe i save coodinate (whit button "save Coordinate) of a Item in a network, i receive this mysql error

**SQL: UPDATE `glpi_plugin_positions_positions` SET `x_coordinates` = '-99.71953370991298', `y_coordinates` = '256.31337501943915', `date_mod` = '2023-09-11 12:07:35' WHERE `id` = '2'
  Error: Out of range value for column 'x_coordinates' at row 1**

The problem is your type field, in you mysql create you have:

+---------------+------------------+------+-----+---------+----------------+
| Field         | Type             | Null | Key | Default | Extra          |
+---------------+------------------+------+-----+---------+----------------+
| id            | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| entities_id   | int(10) unsigned | NO   | MUL | 0       |                |
| is_recursive  | tinyint(4)       | NO   |     | 0       |                |
| name          | varchar(255)     | YES  | MUL | NULL    |                |
| locations_id  | int(10) unsigned | NO   |     | 0       |                |
| items_id      | int(10) unsigned | NO   |     | 0       |                |
| itemtype      | varchar(100)     | NO   |     | NULL    |                |
**| x_coordinates | int(10) unsigned | NO   |     | 0       |                |
| y_coordinates | int(10) unsigned | NO   |     | 0       |                |**
| width         | int(10) unsigned | NO   |     | 25      |                |
| height        | int(10) unsigned | NO   |     | 30      |                |
| tooltip       | varchar(255)     | YES  |     | NULL    |                |
| color         | varchar(255)     | YES  |     | NULL    |                |
| outline       | varchar(255)     | YES  |     | NULL    |                |
| outlineWidth  | int(10) unsigned | NO   |     | 1       |                |
| shape         | varchar(255)     | YES  |     | NULL    |                |
| hideLabel     | tinyint(4)       | NO   |     | 0       |                |
| hideTooltip   | tinyint(4)       | NO   |     | 0       |                |
| rotate        | int(10) unsigned | NO   |     | 0       |                |
| pattern       | varchar(255)     | YES  |     | NULL    |                |
| labelSize     | decimal(11,2)    | NO   |     | 1.00    |                |
| notepad       | longtext         | YES  |     | NULL    |                |
| date_mod      | timestamp        | YES  | MUL | NULL    |                |
| is_deleted    | tinyint(4)       | NO   | MUL | 0       |                |
+---------------+------------------+------+-----+---------+----------------+

you set the x and y coordinate with INT  unsigned type that not support negative sign.
so you cannot inser any item because the default value in position.class.php file, at line 168 and 169

   **$input["x_coordinates"] = '-1000';
   $input["y_coordinates"] = '-225';**

after alter filed whit type INT work correctly

 **alter table glpi_plugin_positions_positions modify column x_coordinates int(10);
 alter table glpi_plugin_positions_positions modify column y_coordinates int(10);**

+---------------+------------------+------+-----+---------+----------------+
| Field         | Type             | Null | Key | Default | Extra          |
+---------------+------------------+------+-----+---------+----------------+
| id            | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| entities_id   | int(10) unsigned | NO   | MUL | 0       |                |
| is_recursive  | tinyint(4)       | NO   |     | 0       |                |
| name          | varchar(255)     | YES  | MUL | NULL    |                |
| locations_id  | int(10) unsigned | NO   |     | 0       |                |
| items_id      | int(10) unsigned | NO   |     | 0       |                |
| itemtype      | varchar(100)     | NO   |     | NULL    |                |
**| x_coordinates | int(10)          | YES  |     | NULL    |                |
| y_coordinates | int(10)          | YES  |     | NULL    |                |**
| width         | int(10) unsigned | NO   |     | 25      |                |
| height        | int(10) unsigned | NO   |     | 30      |                |
| tooltip       | varchar(255)     | YES  |     | NULL    |                |
| color         | varchar(255)     | YES  |     | NULL    |                |
| outline       | varchar(255)     | YES  |     | NULL    |                |
| outlineWidth  | int(10) unsigned | NO   |     | 1       |                |
| shape         | varchar(255)     | YES  |     | NULL    |                |
| hideLabel     | tinyint(4)       | NO   |     | 0       |                |
| hideTooltip   | tinyint(4)       | NO   |     | 0       |                |
| rotate        | int(10) unsigned | NO   |     | 0       |                |
| pattern       | varchar(255)     | YES  |     | NULL    |                |
| labelSize     | decimal(11,2)    | NO   |     | 1.00    |                |
| notepad       | longtext         | YES  |     | NULL    |                |
| date_mod      | timestamp        | YES  | MUL | NULL    |                |
| is_deleted    | tinyint(4)       | NO   | MUL | 0       |                |
+---------------+------------------+------+-----+---------+----------------+

Please update you script

Thanks for you works

**Comment by tsmr** [comment]
Fixed in 6.0.3 version
