### ISSUE TITLE
Uncaught Exception Error: Class "Glpi\\Socket" not found in /glpi/marketplace/positions/inc/position.class.php at line 166

### ISSUE THREAD

**Issue by jcervantes-sipecom** [InfotelGLPI/positions#67]
------------
* Version of the plugin : 
6.0.3

* Version of your GLPI : 
10.0.11

* Steps to reproduce (which actions have you made) :

1. Upgrade from 6.0.2 to 6.0.3
2. Go to Tools > Cartographies (marketplace/positions/front/map.form.php)
3. Select a map, Add a Socket
4. Error Raise

* Expected result :
The Socket could be added succesfully.

* Actual result :
Error: Uncaught Exception Error: Class "Glpi\\Socket" not found in /glpi/marketplace/positions/inc/position.class.php at line 166

* URL of the page :
marketplace/positions/front/map.form.php

* Screenshot of the problem (if pertinent) :

![image](https://github.com/InfotelGLPI/positions/assets/56606032/1f79bf5e-4084-490f-85eb-e2a4fd5b7a7a)

![image](https://github.com/InfotelGLPI/positions/assets/56606032/cca36bab-f273-460f-a5fe-b4d52135a6dc)

**Comment by ArthurMinfotel** [comment]
Fixed
